Feature/dsprotection refactoring
cryptimeleon/incentive-system pull request #77
Opened 2022-02-14 19:33 UTC by pschuermann97

## Reason for this PR:

- implemented version 1 of double-spending protection service + wrote unit tests for database handler/integration test for dbSync
- some issues are left (see Github issues)

## Changes in this PR:

- dbSync algo. implemented according to 2020 incentive system paper
- Link, Trace, VerifyDs implemented according to above paper
- database handler for accessing the transaction/token-graph database implemented
    * tested with a mock java.util.HashMap database
    * in system test/production it will run using Spring JDBC and the H2 database implementation 

## Checklist:

Select whatever applies:

- [x] Test written
- [x] Code Properly Formatted
- [x] Documented
- [x] Changelog updated

2022-02-15 13:02 UTC, this-kramer requested changes
Nice, only some minor things to fix.
One aspect I definitely would like to be fixed (in a future branch) is that there is no test for dsprot in crypto (to get our nice test coverage and make sure it works in a simple test setting)

2022-03-02 07:09 UTC, pschuermann97 commented on crypto/build.gradle
> +    api 'com.google.code.gson:gson:2.8.6'
This indeed is a relic, thanks for pointing out

2022-03-05 08:57 UTC, pschuermann97 commented on crypto/src/main/java/org/cryptimeleon/incentive/crypto/IncentiveSystem.java
> +     */
Added it, also wrote some more docu for TraceOutput and DoubleSpending tag classes.

2022-03-05 09:12 UTC, pschuermann97 commented on crypto/src/main/java/org/cryptimeleon/incentive/crypto/model/TraceOutput.java
> +
Added as a fix for an earlier suggestion

2022-03-05 09:20 UTC, pschuermann97 commented on crypto/src/main/java/org/cryptimeleon/incentive/crypto/dsprotectionlogic/DatabaseHandler.java
> +    public long getUserInfoCount();
They are used in the test classes for the double-spending protection service e.g. DbSyncIntegrationTest, ...

2022-03-05 09:22 UTC, pschuermann97 commented on crypto/src/main/java/org/cryptimeleon/incentive/crypto/IncentiveSystem.java
> +        System.out.println("Started database synchronization process.");
This is code in crypto so it cannot spam the dsprotectionservice logs afaik ^^

2022-03-05 09:27 UTC, pschuermann97 commented on crypto/src/main/java/org/cryptimeleon/incentive/crypto/model/Transaction.java
> +@Setter
Feel like I got confused here with Transaction vs TransactionEntry (the latter cannot be immutable)

2022-03-05 09:32 UTC, pschuermann97 commented on crypto/src/main/java/org/cryptimeleon/incentive/crypto/model/DoubleSpendingTag.java
> +@Setter
Apparently the answer is no. Same as for Transaction

2022-03-05 09:34 UTC, pschuermann97 commented on services/client/src/test/java/org/cryptimeleon/incentive/client/integrationtest/FullWorkflowTest.java
> +// TODO: also test deduct service
Outdated comment.
I always love TODOs disappearing like this

2022-03-05 09:45 UTC, pschuermann97 commented on crypto/src/test/java/org/cryptimeleon/incentive/crypto/Helper.java
> -public class Helper {
It was not me who moved it to the main package I think

2022-03-05 09:49 UTC, pschuermann97 commented on services/dsprotectionservice/build.gradle
> +
So why is the double dependency there then?
I do not recall adding it ^^

2022-03-05 09:58 UTC, pschuermann97 commented on services/dsprotectionservice/src/main/java/org/cryptimeleon/incentivesystem/dsprotectionservice/DsprotectionController.java
> +     * Clears all tables of the double-spending database.
... or just delete it since it is never used ^^

2022-03-05 10:02 UTC, pschuermann97 commented on services/dsprotectionservice/settings.gradle
> +rootProject.name = 'dsprotectionservice'
Done. Seemed to be useless anyway.

2022-03-05 10:04 UTC, pschuermann97 commented on services/dsprotectionservice/build.gradle
> +}
Done

2022-03-05 10:08 UTC, pschuermann97 commented on services/dsprotectionservice/src/main/java/org/cryptimeleon/incentivesystem/dsprotectionservice/LocalDatabaseHandler.java
> +    private WebClient dsProtectionClient;
Removed it, outdated line from old database API

2022-03-06 09:22 UTC, pschuermann97 commented on crypto/src/main/java/org/cryptimeleon/incentive/crypto/model/Transaction.java
> +    public Transaction(IncentivePublicParameters pp, boolean isValid, String serializedTransactionIDRepr, String k,
Good question, 10 points for Gryffindor.
Turns out it was a relic from my confusion during the early stages of the double-spending DB implementations.
I rewrote two constructor calls and removed this constructor.

2022-03-10 15:19 UTC, this-kramer commented on services/dsprotectionservice/build.gradle
> +
Well it was you though according to git :laughing:

2022-03-10 16:03 UTC, this-kramer commented on services/dsprotectionservice/build.gradle
> +
Fixed it

2022-03-11 20:03 UTC, merged